# Generated by Django 5.0.2 on 2024-06-07 16:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='service_title', unique=True),
        ),
    ]
